volumes:
  postgres-db-test:
  logs-data-test:

networks:
  test-network:
    driver: bridge

services:
  db-test:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env.test
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    ports:
      - 5434:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d test']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - test-network

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - logs-data-test:/home/node/app/logs
    command: npm run test:unit
    networks:
      - test-network
