FROM node:20-alpine
WORKDIR /home/node/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate --schema ./prisma/schema.prisma
RUN mkdir -p /home/node/app/logs && chown -R node:node /home/node/app/logs
USER node
